<?xml version="1.0"?>
<robot name="gallipoli_auv" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:include filename="$(find uuv_descriptions)/urdf/common.urdf.xacro"/>
  <xacro:include filename="$(find uuv_sensor_ros_plugins)/urdf/sensor_snippets.xacro"/>
  <xacro:include filename="$(find uuv_gazebo_ros_plugins)/urdf/snippets.xacro"/>  
  <!-- <xacro:include filename="$(find gallipoli_auv_description)/urdf/snippets.xacro"/> -->
  <xacro:include filename="$(find gallipoli_auv_description)/urdf/sensor_snippets.xacro" />
	<xacro:include filename="$(find gallipoli_auv_description)/urdf/actuator_snippets.xacro" />

  
  <!--
    Vehicle's parameters (remember to enter the model parameters below)
  -->

  <xacro:property name="mass" value="10"/>
  <xacro:property name="volume" value="0.015"/>

  <xacro:property name="cog" value="0 -0.0135 0"/>
  <xacro:property name="cob" value="0 0 0"/>
  <xacro:property name="rho" value="1028"/>

  <xacro:property name="length" value="0.45"/>
  <xacro:property name="width"  value="0.245"/>
  <xacro:property name="height" value="0.54"/>

  <xacro:property name="radius"  value="${0.5 * height}"/>


  <xacro:property name="visual_mesh_file" value="file://$(find gallipoli_auv_description)/meshes/body.dae"/>
  <xacro:property name="collision_mesh_file" value="file://$(find gallipoli_auv_description)/meshes/body.stl"/>

  <!-- Vehicle macro -->
  <xacro:macro name="gallipoli_auv_base" params="namespace debug inertial_reference_frame">

      <!-- Rigid body description of the base link -->
      <link name="${namespace}/base_link">

        <inertial>
          <mass value="${mass}" />
          <origin xyz="${cog}" rpy="0 0 0"/>
          <inertia ixx="${0.2*mass*width*width + 0.2*mass*height*height}" ixy="0.0" ixz="0.0"
                  iyy="${0.2*mass*length*length + 0.2*mass*height*height}" iyz="0.0"
                  izz="${0.2*mass*length*length + 0.2*mass*width*width}" />
        </inertial>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <mesh filename="${visual_mesh_file}" scale="1 1 1" />
          </geometry>
        </visual>

        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <mesh filename="${collision_mesh_file}" scale="1 1 1" />
          </geometry>
        </collision>
      </link>

    <gazebo reference="${namespace}/base_link">
      <selfCollide>false</selfCollide>
    </gazebo>

    <!-- Set up hydrodynamic plugin -->
    <gazebo>
      <plugin name="${namespace}_uuv_plugin" filename="libuuv_underwater_object_ros_plugin.so">
        <fluid_density>${rho}</fluid_density>
        <flow_velocity_topic>hydrodynamics/current_velocity</flow_velocity_topic>
        <debug>${debug}</debug>
        <link name="${namespace}/base_link">
          <neutrally_buoyant>0</neutrally_buoyant>
          <volume>${volume}</volume>
          <box>
            <width>${width}</width>
            <length>${length}</length>
            <height>${height}</height>
          </box>
          <center_of_buoyancy>${cob}</center_of_buoyancy>
          <hydrodynamic_model>
            <type>fossen</type>
            <added_mass>
              ${mass*0.2404}  0       0       0       0       0
              0       ${mass*0.9024}  0       0       0       0
              0       0       ${mass*0.8283}  0       0       0
              0       0       0       0.2222  0       0
              0       0       0       0       0.1492  0
              0       0       0       0       0       0.3209
            </added_mass>
            <linear_damping>
              -19.5909 -19.5909 -50.5595 -13.3040 -13.2181 -1.1559
            </linear_damping>
            <quadratic_damping>
              -5.1386 -5.1386 -26.1105 0 0 0
            </quadratic_damping>
          </hydrodynamic_model>
        </link>
      </plugin>
    </gazebo>

    <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
          <robotNamespace>/gallipoli_auv</robotNamespace>
      </plugin>
    </gazebo>

    <xacro:include filename="$(find gallipoli_auv_description)/urdf/actuators.xacro"/>
    <xacro:include filename="$(find gallipoli_auv_description)/urdf/sensors.xacro"/>

  </xacro:macro>

</robot>
